# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           http://jengrdnr.github.io/
plugins:             [jekyll-paginate,jekyll-paginate-v2]
