# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Got To Eat
paginate:       5
baseurl:        ""
url:            "http://gottoeat.co.uk"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jennie McLoughlin
  url:          http://gottoeat.co.uk
  email:        jen@grdnr.io

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/jengrdnr/jen-blog

# Gems
gems:
  - jekyll-paginate
